package ug.daes.onboarding.enums;

public enum ServiceNames {

	SERVICE_PROVIDER_ONBOARDED
	, SUBSCRIBER_ONBOARDED     
	, CERTIFICATE_PAIR_ISSUED  
	, SUBSCRIBER_AUTHENTICATED 
	, DIGITALLY_SIGNED         
	, KEY_PAIR_GENERATED       
	, CSR_CREATED              
	, CERTIFICATE_GENERATED    
	, PKI_AUTHENTICATED        
	, SIGNATURE_VERIFIED       
	, OTHER
	,REGISTRATION_OTP_SENT
	,SUBSCRIBER_REGISTRATION

}
